### PR TITLE
Add KIBANA_LOC to web config

### PR DESCRIPTION
**Pull request by ptcNOP**
This is needed for the system info tab.

TODO:
- Hardcoded kibana port, can we get kibana vars from here?

### CODE REVIEW

**Comment by awest1339** [comment]
Could we just add a variable that defines the kibana port? That's what we do elsewhere.

**Comment by ptcNOP** [comment]
`kibana_ports` is defined in `group_vars/kibana`. So I guess my question is, can we access those vars outside of the kibana role or should we move it to `group_vars/all`?

**Comment by awest1339** [comment]
I could be wrong, but my understanding is that role variables are only available within that role. I think we may have to move the variable to `group_vars/all`

**Comment by ptcNOP** [comment]
Okay, that's what I was thinking too. I'll move it to `group_vars/all` and update the other places it's used.

**Pull request closed without merging**
